### PR TITLE
BUG: install test data

### PR DESCRIPTION
**Pull request by mgorny**
Fix the setup script to install the data for tests.  This is necessary
for test_template.py to pass.

### CODE REVIEW

**Comment by rdbisme** [comment]
Hello, could you add a test somewhere to trigger this? Because the tests are passing in the CI using `pytest` on the local repository. Or, are tests really needed to be shipped with the package?

**Comment by mgorny** [comment]
> Hello, could you add a test somewhere to trigger this? Because the tests are passing in the CI using `pytest` on the local repository.

As in, a test that triggers the actual failure? Or should I try to modify the CI to test on of the installed package to trigger this?

> Or, are tests really needed to be shipped with the package?

I don't have an opinion either way. They were shipped originally, so I assumed that this is desirable.

**Comment by rdbisme** [comment]
> As in, a test that triggers the actual failure? Or should I try to modify the CI to test on of the installed package to trigger this?
The one that is faster :)

**Comment by mgorny** [comment]
Done. The first commit switches to non-develop install and uses `pytest --pyargs` to run tests from installed package rather than the current directory. It [breaks tests](https://github.com/mgorny/bottleneck/actions/runs/1884120856).

The second commit [fixes them afterwards](https://github.com/mgorny/bottleneck/actions/runs/1884136193).

**Comment by rdbisme** [comment]
Thanks!

**Pull request merged**
