### PR TITLE
MNT: Enable Renovate

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/marketplace/renovate

### CODE REVIEW

**Comment by rdbisme** [comment]
Thanks @gliptak. How does it compare to dependabot?

**Comment by gliptak** [comment]
@rdbisme similar, although Renovate seems to offer better out-of-the-box configuraton

Consider merging this and you can reconfigure/remove later

**Comment by rdbisme** [comment]
Ok, do I need to do something else after merging?

**Comment by gliptak** [comment]
@rdbisme I see no PRs. please add app/permission to the repo/org at https://github.com/marketplace/renovate

**Comment by rdbisme** [comment]
I can't set the permissions for a project not in my root namespace.

Since this is under `pydata` org, I can't set it up.

**Comment by gliptak** [comment]
Unfortunately https://github.com/orgs/pydata/people doesn't allow listing of Admins

**Pull request merged**
