### PR TITLE
Numpy version freeze

### PR DESCRIPTION
**Pull request by didacSF**

### CODE REVIEW

**Comment by qwhelan** [comment]
Hi @didacSF - thanks for the PR. Could you provide a bit more detail on the issue you're encountering?

I'm about to cut a release candidate with the intent to support older versions of numpy for py2.7. After this release, py2 will be dropped and numpy min version can be increased.

**Comment by didacSF** [comment]
Hi @qwhelan my issue appeared while trying to install bottleneck using pip in a clean Python 2.7 venv environment, since the module tried to install numpy-1.17 which doesn't work on Python 2.7 I had to install numpy 1.16 first manually before I could install this one.

My intention was more or less the same that you mentioned in you comment: having a final version that has confirmed support for Python 2.7. So if that was already the plan, then this PR probably is unnecessary.

**Comment by qwhelan** [comment]
@didacSF Could you provide a little more detail on your environment?
- Operating System
- Anaconda vs non-Anaconda

Thanks!

**Comment by qwhelan** [comment]
I was able to see an issue with numpy 1.17 when simply `pip install bottleneck`, which is expected.

Running against `HEAD` appears to work:
```
pip install ~/code/bottleneck
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /home/chris/code/bottleneck
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
     |████████████████████████████████| 17.0MB 3.5MB/s 
Building wheels for collected packages: Bottleneck
  Building wheel for Bottleneck (PEP 517) ... done
  Created wheel for Bottleneck: filename=Bottleneck-1.3.0.dev0+131.g202188f-cp27-cp27mu-linux_x86_64.whl size=370380 sha256=396d802d5285f248810a532deac29b3b136cc807e52627e9f1ebfc8b67bf177d
  Stored in directory: /tmp/pip-ephem-wheel-cache-BVa3mP/wheels/ce/58/1a/6a7d381fc608a4f269401ad749f58ed88902c54bdbf0169717
Successfully built Bottleneck
Installing collected packages: numpy, Bottleneck
Successfully installed Bottleneck-1.3.0.dev0+131.g202188f numpy-1.16.5
```

**Comment by didacSF** [comment]
Hi @qwhelan this are my specs:

- OS: Ubuntu 18.04.3 LTS
- Not using Anaconda
- pip 19.3.1 in python 2.7.15+ venv
- Installed using pip

Hope that helps you.

**Comment by qwhelan** [comment]
Does this work for you?
```
pip install --pre bottleneck==1.3.0rc1
```

**Comment by didacSF** [comment]
Yep, it did work fine, I've run the command in an empty Python2.7 venv and this is what I got:
```sh
(test2.7) didac@didac-OptiPlex-3050:~$ pip install --pre bottleneck==1.3.0rc1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting bottleneck==1.3.0rc1
  Downloading https://files.pythonhosted.org/packages/a0/df/07b998e461efc8903613c4b62faf0f69371129b8cb6d6d69a5c6a1dc15b8/Bottleneck-1.3.0rc1.tar.gz (87kB)
     |████████████████████████████████| 92kB 1.7MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl
Building wheels for collected packages: bottleneck
  Building wheel for bottleneck (PEP 517) ... done
  Created wheel for bottleneck: filename=Bottleneck-1.3.0rc1-cp27-cp27mu-linux_x86_64.whl size=314704 sha256=a1e583421a36d1755a14d1406f5eba8f7d991f4e0ed7e39b27fb5c3acfeaa30d
  Stored in directory: /home/didac/.cache/pip/wheels/00/af/71/bf17e282e348b2a5e07d5fe5844c9db243835509bb21b92faf
Successfully built bottleneck
Installing collected packages: numpy, bottleneck
Successfully installed bottleneck-1.3.0rc1 numpy-1.16.5
```

**Comment by qwhelan** [comment]
Fantastic, thanks for verifying that! Full release should be later this week, so the normal command should work again soon

**Comment by didacSF** [comment]
Ok, many thanks for you efforts!

I'll close this PR if that is fine with you.

**Pull request closed without merging**
